[package]
name = "fifth-homework"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.218", features = ["derive"] }
flume = "0.11.1"
serde_json = "1.0.139"
image = "0.25.5"
chrono = "0.4.39"
